# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 802e0c48c4138cd0f46d908fa3ad9f7d6d70e0e4bf3ffb6f4a3444cddaa1fd12f90a9f092793ffabc1ed93e7bf27af211a9782778c94352ce6fc8b9848ccc04f

test:
  secret_key_base: 3c404c313e949d22e284194561b8488ca159f6b628e854fa259dfdbbeef05b58b2e5a236b9f0850c81f300877c0adadde0327b82de7b682a1b1fc2bbdbdbc86a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
